<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BahanBakuSeeder extends Seeder
{
    public function run(): void
    {
        $bahanBaku = [
            ['nama' => 'Concumption', 'satuan' => 'ORDER'],
            ['nama' => 'Caramel Syrup', 'satuan' => 'ML'],
            ['nama' => 'Lychee Syrup', 'satuan' => 'ML'],
            ['nama' => 'Straberry Syrup', 'satuan' => 'ML'],
            ['nama' => 'Butterscotch Syrup', 'satuan' => 'ML'],
            ['nama' => 'Peach Syrup', 'satuan' => 'ML'],
            ['nama' => 'Vanila Syrup', 'satuan' => 'ML'],
            ['nama' => 'Hazelnut Syrup', 'satuan' => 'ML'],
            ['nama' => 'Simple Syrup', 'satuan' => 'ML'],
            ['nama' => 'Aren', 'satuan' => 'ML'],
            ['nama' => 'Taro Powder', 'satuan' => 'GRAM'],
            ['nama' => 'Red Velvet Powder', 'satuan' => 'GRAM'],
            ['nama' => 'Chocolate Ab Sweet', 'satuan' => 'GRAM'],
            ['nama' => 'Chocolate Dark', 'satuan' => 'GRAM'],
            ['nama' => 'Matca', 'satuan' => 'GRAM'],
            ['nama' => 'Creamer', 'satuan' => 'GRAM'],
            ['nama' => 'Skm', 'satuan' => 'GRAM'],
            ['nama' => 'Freshmilk', 'satuan' => 'ML'],
            ['nama' => 'Possion Fruit Syrup', 'satuan' => 'ML'],
            ['nama' => 'Lychee Garnish', 'satuan' => 'GRAM'],
            ['nama' => 'Lemon Fruit', 'satuan' => 'PCS'],
            ['nama' => 'Straberry Garnish', 'satuan' => 'PCS'],
            ['nama' => 'Lemon  Garnish', 'satuan' => 'PCS'],
            ['nama' => 'Biscuit Regal', 'satuan' => 'GRAM'],
            ['nama' => 'Seasalt', 'satuan' => 'GRAM'],
            ['nama' => 'Tea Mix', 'satuan' => 'GRAM'],
            ['nama' => 'Full Arabica Coffee', 'satuan' => 'GRAM'],
            ['nama' => 'Beans Filter Coffee', 'satuan' => 'GRAM'],
            ['nama' => 'Mineral Water', 'satuan' => 'PCS'],
            ['nama' => 'Gulaku Sachet', 'satuan' => 'PCS'],
            ['nama' => 'Caramel Topping', 'satuan' => 'ML'],
            ['nama' => 'Rich\'S Gold', 'satuan' => 'ML'],
            ['nama' => 'Galon Cleo 19l', 'satuan' => 'ML'],
            ['nama' => 'Tepung Maizena', 'satuan' => 'GRAM'],
            ['nama' => 'Tepung Cakra', 'satuan' => 'GRAM'],
            ['nama' => 'Tepung Segitiga', 'satuan' => 'GRAM'],
            ['nama' => 'Tepung Panir', 'satuan' => 'GRAM'],
            ['nama' => 'Tepung Beras', 'satuan' => 'GRAM'],
            ['nama' => 'Mayonaise', 'satuan' => 'GRAM'],
            ['nama' => 'Souce Tomat', 'satuan' => 'ML'],
            ['nama' => 'Souce Chili', 'satuan' => 'ML'],
            ['nama' => 'Minyak Goreng', 'satuan' => 'ML'],
            ['nama' => 'Gula Jawa', 'satuan' => 'GRAM'],
            ['nama' => 'Beras', 'satuan' => 'GRAM'],
            ['nama' => 'Spaghetti', 'satuan' => 'GRAM'],
            ['nama' => 'Fertuccine', 'satuan' => 'GRAM'],
            ['nama' => 'Pure Raw Honey', 'satuan' => 'ML'],
            ['nama' => 'Kemiri', 'satuan' => 'GRAM'],
            ['nama' => 'Lada', 'satuan' => 'GRAM'],
            ['nama' => 'Lada Hitam', 'satuan' => 'GRAM'],
            ['nama' => 'Jinten', 'satuan' => 'GRAM'],
            ['nama' => 'Kunyit Bubuk', 'satuan' => 'GRAM'],
            ['nama' => 'Ketumbar', 'satuan' => 'GRAM'],
            ['nama' => 'Wijen', 'satuan' => 'GRAM'],
            ['nama' => 'Cengkeh', 'satuan' => 'GRAM'],
            ['nama' => 'Pala', 'satuan' => 'PCS'],
            ['nama' => 'Kecap', 'satuan' => 'ML'],
            ['nama' => 'Oregano', 'satuan' => 'GRAM'],
            ['nama' => 'Cuka', 'satuan' => 'ML'],
            ['nama' => 'Gula Palm', 'satuan' => 'GRAM'],
            ['nama' => 'Kerupuk Udang', 'satuan' => 'GRAM'],
            ['nama' => 'Bawang Goreng', 'satuan' => 'GRAM'],
            ['nama' => 'Mustard', 'satuan' => 'ML'],
            ['nama' => 'Royco', 'satuan' => 'GRAM'],
            ['nama' => 'Garam', 'satuan' => 'GRAM'],
            ['nama' => 'Micin', 'satuan' => 'GRAM'],
            ['nama' => 'Nori', 'satuan' => 'GRAM'],
            ['nama' => 'Souce Bolognese', 'satuan' => 'ML'],
            ['nama' => 'Mentega', 'satuan' => 'GRAM'],
            ['nama' => 'Saori Saus Tiram', 'satuan' => 'ML'],
            ['nama' => 'Saori Saus Teriyaki', 'satuan' => 'ML'],
            ['nama' => 'Kecap Asin', 'satuan' => 'ML'],
            ['nama' => 'Minyak Wijen', 'satuan' => 'ML'],
            ['nama' => 'Minyak Ikan', 'satuan' => 'ML'],
            ['nama' => 'Fermipan', 'satuan' => 'GRAM'],
            ['nama' => 'Chocochip', 'satuan' => 'GRAM'],
            ['nama' => 'Milk Powder', 'satuan' => 'GRAM'],
            ['nama' => 'Terasi', 'satuan' => 'PCS'],
            ['nama' => 'Vanili', 'satuan' => 'ML'],
            ['nama' => 'Wijen Sangrai', 'satuan' => 'ML'],
            ['nama' => 'Nescafe', 'satuan' => 'PCS'],
            ['nama' => 'Bawang Putih', 'satuan' => 'GRAM'],
            ['nama' => 'Baking Soda', 'satuan' => 'GRAM'],
            ['nama' => 'Baking Powder', 'satuan' => 'GRAM'],
            ['nama' => 'Tomate Paste', 'satuan' => 'ML'],
            ['nama' => 'Asam Jawa', 'satuan' => 'PCS'],
            ['nama' => 'Straw', 'satuan' => 'GRAM'],
            ['nama' => 'Hand Soap', 'satuan' => 'ML'],
            ['nama' => 'Pel Lantai Sos', 'satuan' => 'ML'],
            ['nama' => 'Detergent (Rinso/Daia)', 'satuan' => 'ML'],
            ['nama' => 'Plastik Ta Cup', 'satuan' => 'GRAM'],
            ['nama' => 'Plastik Ta Kecil', 'satuan' => 'GRAM'],
            ['nama' => 'Plastik Ta Tanggung', 'satuan' => 'GRAM'],
            ['nama' => 'Trash Bag', 'satuan' => 'GRAM'],
            ['nama' => 'Plastik Opp Sendok', 'satuan' => 'GRAM'],
            ['nama' => 'Tusuk Buah', 'satuan' => 'GRAM'],
            ['nama' => 'Cling Pem Kaca', 'satuan' => 'ML'],
            ['nama' => 'Tissue', 'satuan' => 'GRAM'],
            ['nama' => 'Wraping', 'satuan' => 'PCS'],
            ['nama' => 'Paperbag Roti', 'satuan' => 'GRAM'],
            ['nama' => 'Lmg (Kertas Nasi)', 'satuan' => 'GRAM'],
            ['nama' => 'Carton Box Take Away', 'satuan' => 'GRAM'],
            ['nama' => 'Thermal Roll 58mm', 'satuan' => 'PCS'],
            ['nama' => 'Tutup Cup', 'satuan' => 'PCS'],
            ['nama' => 'Cup Lid 14oz', 'satuan' => 'PCS'],
            ['nama' => 'Tusukan Garnise', 'satuan' => 'GRAM'],
            ['nama' => 'Daun Mint', 'satuan' => 'PCS'],
            ['nama' => 'Bawang Merah', 'satuan' => 'GRAM'],
            ['nama' => 'Gula Pasir', 'satuan' => 'GRAM'],
            ['nama' => 'Selada', 'satuan' => 'GRAM'],
            ['nama' => 'Roti Tawar', 'satuan' => 'GRAM'],
            ['nama' => 'Loncang', 'satuan' => 'GRAM'],
            ['nama' => 'Koll Ungu', 'satuan' => 'GRAM'],
            ['nama' => 'Bombay', 'satuan' => 'PCS'],
            ['nama' => 'Tempe', 'satuan' => 'PCS'],
            ['nama' => 'Mozarella', 'satuan' => 'GRAM'],
            ['nama' => 'Tomate', 'satuan' => 'GRAM'],
            ['nama' => 'Jamur Champignon', 'satuan' => 'GRAM'],
            ['nama' => 'Tomate Cery', 'satuan' => 'GRAM'],
            ['nama' => 'Koll Putih', 'satuan' => 'GRAM'],
            ['nama' => 'Touge', 'satuan' => 'GRAM'],
            ['nama' => 'Cabe Ijo Rawit', 'satuan' => 'GRAM'],
            ['nama' => 'Cabe Keriting Merah', 'satuan' => 'GRAM'],
            ['nama' => 'Cabe Rawit', 'satuan' => 'GRAM'],
            ['nama' => 'Cabe Ijo Panjang', 'satuan' => 'GRAM'],
            ['nama' => 'Bumbu Pawon', 'satuan' => 'GRAM'],
            ['nama' => 'Timun', 'satuan' => 'GRAM'],
            ['nama' => 'Ayam Filed Paha', 'satuan' => 'GRAM'],
            ['nama' => 'Bread Improver', 'satuan' => 'GRAM'],
            ['nama' => 'Wortel', 'satuan' => 'GRAM'],
            ['nama' => 'Kentang', 'satuan' => 'GRAM'],
            ['nama' => 'Tisu Dapur', 'satuan' => 'PCS'],
            ['nama' => 'Sunlight', 'satuan' => 'ML'],
            ['nama' => 'Parsley Fresh', 'satuan' => 'GRAM'],
            ['nama' => 'Chicken Steak', 'satuan' => 'PCS'],
            ['nama' => 'Keju Cheddar', 'satuan' => 'PCS'],
            ['nama' => 'Bakso Sapi', 'satuan' => 'GRAM'],
            ['nama' => 'Cordon Bleu', 'satuan' => 'PCS'],
            ['nama' => 'Smoked Beef', 'satuan' => 'PCS'],
            ['nama' => 'Ayam Goreng', 'satuan' => 'PCS'],
            ['nama' => 'Cireng', 'satuan' => 'PCS'],
            ['nama' => 'Spaggetti', 'satuan' => 'PCS'],
            ['nama' => 'Fettucine', 'satuan' => 'PCS'],
            ['nama' => 'Frenchfries Mix', 'satuan' => 'PCS'],
            ['nama' => 'Frenchfries Krinkle', 'satuan' => 'PCS'],
            ['nama' => 'Sosis', 'satuan' => 'PCS'],
            ['nama' => 'Nugget', 'satuan' => 'PCS'],
            ['nama' => 'Risole', 'satuan' => 'PCS'],
            ['nama' => 'Telur', 'satuan' => 'PCS'],
            ['nama' => 'Cireng Mix', 'satuan' => 'PCS'],
            ['nama' => 'Selada Romaine', 'satuan' => 'GRAM'],
            ['nama' => 'Barbeque Sauce', 'satuan' => 'ML'],
            ['nama' => 'Totole', 'satuan' => 'GRAM'],
            ['nama' => 'Timus', 'satuan' => 'PCS'],
            ['nama' => 'Bawang Putih Bubuk', 'satuan' => 'PCS'],
            ['nama' => 'Demiglace', 'satuan' => 'GRAM'],
            ['nama' => 'Sosis Nasi Goreng', 'satuan' => 'PCS'],
            ['nama' => 'Pakcoy', 'satuan' => 'GRAM'],
            ['nama' => 'Spaghetti Sauce', 'satuan' => 'ML'],
            ['nama' => 'Cumi', 'satuan' => 'PCS'],
            ['nama' => 'Udang', 'satuan' => 'PCS'],
            ['nama' => 'Iga', 'satuan' => 'PCS'],
            ['nama' => 'Bakso Ikan', 'satuan' => 'PCS'],
            ['nama' => 'Kulit Crispy', 'satuan' => 'PCS'],
            ['nama' => 'Rica Ayam', 'satuan' => 'GRAM'],
        ];

        $insertData = [];
        $now = now();
        foreach ($bahanBaku as $item) {
            $insertData[] = [
                'nama' => $item['nama'],
                'satuan' => $item['satuan'],
                'harga_beli_terakhir' => 0,
                'stok_minimum' => 0,
                'stok_saat_ini' => 0,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('inventory_bahan_baku')->insert($insertData);
    }
}
